
import React from 'react';
import {
  Utensils,
  ShoppingCart,
  Pill,
  ShoppingBag,
  Wrench,
  Home as HomeIcon,
  Car,
  MessageCircle,
  MapPin,
  Clock,
  Truck,
  Package,
  Search,
  Menu,
  X,
  Plus,
  Trash2,
  Edit,
  ArrowRight,
  Newspaper,
  Shirt,
  PawPrint,
  HeartPulse,
  GraduationCap,
  Hammer,
  PartyPopper,
  Filter,
  Eye,
  Music,
  Palette,
  Theater,
  CalendarDays,
  Ticket,
  Briefcase,
  UserCheck,
  ExternalLink,
  Info,
  Instagram,
  BadgeCheck,
  Star,
  Check,
  Dumbbell,
  Smartphone,
  Lamp,
  Palmtree,
  Beef,
  Baby
} from 'lucide-react';
import { CategoryType } from './types';

export const ICONS = {
  Utensils,
  ShoppingCart,
  Pill,
  ShoppingBag,
  Wrench,
  HomeIcon,
  Car,
  MessageCircle,
  MapPin,
  Clock,
  Truck,
  Package,
  Search,
  Menu,
  X,
  Plus,
  Trash2,
  Edit,
  ArrowRight,
  Newspaper,
  Filter,
  Eye,
  Music,
  Palette,
  Theater,
  CalendarDays,
  Ticket,
  PartyPopper,
  Briefcase,
  UserCheck,
  ExternalLink,
  Info,
  Instagram,
  BadgeCheck,
  Star,
  Check,
  Dumbbell,
  Smartphone,
  Lamp,
  Palmtree,
  Beef,
  Baby
};

export const CATEGORY_ICONS: Record<CategoryType, React.ReactNode> = {
  [CategoryType.RESTAURANTES]: <Utensils className="w-6 h-6" />,
  [CategoryType.MERCADOS]: <ShoppingCart className="w-6 h-6" />,
  [CategoryType.FARMACIAS]: <Pill className="w-6 h-6" />,
  [CategoryType.LOJAS]: <ShoppingBag className="w-6 h-6" />,
  [CategoryType.SERVICOS]: <Wrench className="w-6 h-6" />,
  [CategoryType.IMOVEIS]: <HomeIcon className="w-6 h-6" />,
  [CategoryType.AUTOMOTIVO]: <Car className="w-6 h-6" />,
  [CategoryType.MODA]: <Shirt className="w-6 h-6" />,
  [CategoryType.PET_SHOP]: <PawPrint className="w-6 h-6" />,
  [CategoryType.SAUDE_BELEZA]: <HeartPulse className="w-6 h-6" />,
  [CategoryType.ACADEMIAS]: <Dumbbell className="w-6 h-6" />,
  [CategoryType.ELETRONICOS]: <Smartphone className="w-6 h-6" />,
  [CategoryType.CASA_DECORACAO]: <Lamp className="w-6 h-6" />,
  [CategoryType.LAZER]: <Palmtree className="w-6 h-6" />,
  [CategoryType.SUPLEMENTOS]: <Beef className="w-6 h-6" />,
  [CategoryType.INFANTIL]: <Baby className="w-6 h-6" />,
  [CategoryType.EDUCACAO]: <GraduationCap className="w-6 h-6" />,
  [CategoryType.CONSTRUCAO]: <Hammer className="w-6 h-6" />,
  [CategoryType.EVENTOS]: <PartyPopper className="w-6 h-6" />,
};

export const PIRACICABA_NEIGHBORHOODS: string[] = [
  "Centro", "Cidade Alta", "Alto", "São Dimas", "Nova Piracicaba", "Alemães", "Vila Rezende", "Vila Independência", "Vila Monteiro", "Vila Boyes", "Clube de Campo", "Morumbi",
  "Vila Sônia", "Santa Terezinha", "Parque Piracicaba (Balbo)", "Jardim São Matheus", "Jardim Conceição", "Jardim Itapuã", "Jardim Primavera", "Jardim Brasília", "Jardim Ipanema", "Jardim Oriente", "Jardim Santa Rosa", "Jardim Caxambu", "Jardim São Francisco", "Jardim São Luiz", "Jardim Piracicaba", "Jardim Alvorada", "Jardim Abaeté", "Jardim Planalto", "Jardim Algodoal", "Jardim Gilda", "Jardim Itamaracá", "Jardim Vitória", "Jardim Bartira",
  "Água Branca", "Jardim Elite", "Jardim Europa", "Nova América", "Jardim Califórnia", "Jardim Panorama", "Jardim Petrópolis", "Jardim Astúrias", "Jardim Glória", "Jardim São Jorge", "Jardim São Judas", "Jardim São Vicente", "Jardim Paraíso", "Jardim Santa Silvia",
  "Pompéia", "Campestre", "Monte Alegre", "Ondas", "Jardim Colina Verde", "Jardim Ibirapuera", "Jardim São Cristóvão", "Jardim São Gabriel", "Jardim São Paulo",
  "Paulicéia", "Jaraguá", "Jardim Nova Iguaçu", "Jardim Maria Cláudia", "Jardim Santo Antônio", "Jardim Tatuapé", "Jardim Itapuã II", "Jardim Caxambu II", "Jardim São Benedito",
  "Ártemis", "Ibitiruna", "Tupi", "Santana", "Guamium", "Piracicamirim", "Dois Córregos"
].sort((a, b) => a.localeCompare(b, 'pt-BR'));

export const WHATSAPP_ADMIN = "5519995901620";
export const WHATSAPP_MSG_DEFAULT = "Olá, encontrei seu comércio no Guia-me Piracicaba e gostaria de mais informações.";
export const INSTAGRAM_URL = "https://www.instagram.com/guiamepiracicaba";

export const BUSINESS_SPECIALTIES = [
  "Academia",
  "Açougue",
  "Alimentação",
  "Atacadista",
  "Automotivo",
  "Artigos de Lazer",
  "Bar / Choperia",
  "Barbearia",
  "Brinquedos",
  "Cafeteria / Doceria",
  "Construção",
  "Consultório / Clínica",
  "Educação / Cursos",
  "Eletrônicos",
  "Eventos / Festas",
  "Farmácia",
  "Fast Food",
  "Hambúrgueria",
  "Imobiliária",
  "Informática",
  "Livraria",
  "Loja de Roupas / Moda",
  "Mercado / Supermercado",
  "Moda Infantil",
  "Móveis / Decoração",
  "Padaria",
  "Papelaria",
  "Pet Shop / Veterinária",
  "Pizzaria",
  "Posto de Combustível",
  "Restaurante",
  "Salão de Beleza",
  "Serviços Gráficos",
  "Sorveteria",
  "Suplementos",
  "Tecnologia",
  "Transporte / Logística",
  "Outros"
].sort();
