
import React from 'react';
import {
  Utensils,
  ShoppingCart,
  Pill,
  ShoppingBag,
  Wrench,
  Home as HomeIcon,
  Car,
  MessageCircle,
  MapPin,
  Clock,
  Truck,
  Package,
  Search,
  Menu,
  X,
  Plus,
  Trash2,
  Edit,
  ArrowRight,
  Newspaper,
  Shirt,
  PawPrint,
  HeartPulse,
  GraduationCap,
  Hammer,
  PartyPopper,
  Filter,
  Eye,
  Music,
  Palette,
  Theater,
  CalendarDays,
  Ticket,
  Briefcase,
  UserCheck,
  ExternalLink,
  Info,
  Instagram,
  BadgeCheck,
  Star
} from 'lucide-react';
import { CategoryType } from './types';

export const ICONS = {
  Utensils,
  ShoppingCart,
  Pill,
  ShoppingBag,
  Wrench,
  HomeIcon,
  Car,
  MessageCircle,
  MapPin,
  Clock,
  Truck,
  Package,
  Search,
  Menu,
  X,
  Plus,
  Trash2,
  Edit,
  ArrowRight,
  Newspaper,
  Filter,
  Eye,
  Music,
  Palette,
  Theater,
  CalendarDays,
  Ticket,
  PartyPopper,
  Briefcase,
  UserCheck,
  ExternalLink,
  Info,
  Instagram,
  BadgeCheck,
  Star
};

export const CATEGORY_ICONS: Record<CategoryType, React.ReactNode> = {
  [CategoryType.RESTAURANTES]: <Utensils className="w-6 h-6" />,
  [CategoryType.MERCADOS]: <ShoppingCart className="w-6 h-6" />,
  [CategoryType.OFICIAIS]: <BadgeCheck className="w-6 h-6 text-brand-teal" />,
  [CategoryType.FARMACIAS]: <Pill className="w-6 h-6" />,
  [CategoryType.LOJAS]: <ShoppingBag className="w-6 h-6" />,
  [CategoryType.SERVICOS]: <Wrench className="w-6 h-6" />,
  [CategoryType.IMOVEIS]: <HomeIcon className="w-6 h-6" />,
  [CategoryType.AUTOMOTIVO]: <Car className="w-6 h-6" />,
  [CategoryType.MODA]: <Shirt className="w-6 h-6" />,
  [CategoryType.PET_SHOP]: <PawPrint className="w-6 h-6" />,
  [CategoryType.SAUDE_BELEZA]: <HeartPulse className="w-6 h-6" />,
  [CategoryType.EDUCACAO]: <GraduationCap className="w-6 h-6" />,
  [CategoryType.CONSTRUCAO]: <Hammer className="w-6 h-6" />,
  [CategoryType.EVENTOS]: <PartyPopper className="w-6 h-6" />,
};

export const PIRACICABA_NEIGHBORHOODS: Record<string, string[]> = {
  "Região Central": ["Centro", "Cidade Alta", "Alto", "São Dimas", "Nova Piracicaba", "Alemães", "Vila Rezende", "Vila Independência", "Vila Monteiro", "Vila Boyes", "Clube de Campo", "Morumbi"],
  "Região Norte": ["Vila Sônia", "Santa Terezinha", "Parque Piracicaba (Balbo)", "Jardim São Matheus", "Jardim Conceição", "Jardim Itapuã", "Jardim Primavera", "Jardim Brasília", "Jardim Ipanema", "Jardim Oriente", "Jardim Santa Rosa", "Jardim Caxambu", "Jardim São Francisco", "Jardim São Luiz", "Jardim Noiva da Colina", "Jardim Alvorada", "Jardim Abaeté", "Jardim Planalto", "Jardim Algodoal", "Jardim Gilda", "Jardim Itamaracá", "Jardim Vitória", "Jardim Bartira"],
  "Região Sul": ["Água Branca", "Jardim Elite", "Jardim Europa", "Nova América", "Jardim Califórnia", "Jardim Panorama", "Jardim Petrópolis", "Jardim Astúrias", "Jardim Abaeté", "Jardim Glória", "Jardim São Jorge", "Jardim São Judas", "Jardim São Vicente", "Jardim Paraíso", "Jardim Santa Silvia", "Jardim São Francisco"],
  "Região Leste": ["Pompéia", "Campestre", "Monte Alegre", "Ondas", "Jardim Colina Verde", "Jardim Ibirapuera", "Jardim Oriente", "Jardim São Cristóvão", "Jardim São Gabriel", "Jardim São Paulo"],
  "Região Oeste": ["Paulicéia", "Jaraguá", "Jardim Nova Iguaçu", "Jardim Maria Cláudia", "Jardim Santo Antônio", "Jardim Tatuapé", "Jardim Itapuã II", "Jardim Caxambu II", "Jardim São Benedito"],
  "Distritos e Regiões Rurais": ["Ártemis", "Ibitiruna", "Tupi", "Santana", "Guamium"]
};

export const WHATSAPP_ADMIN = "5519995901620";
export const WHATSAPP_MSG_DEFAULT = "Olá, encontrei seu comércio no Guia-me Piracicaba e gostaria de mais informações.";
export const INSTAGRAM_URL = "https://www.instagram.com/guiamepiracicaba";
